### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by jjanelee97** [lineatkaf/lineatkaf.github.io#3]

**Comment by jcheong0428** [comment]
Do we have the main coffeecup icon with the footprint on it with a blank background that could be used as favicon? 

Also do you remember where is the repo with all the vector icons generated from our previous project? I think it was some .sketch file..? 

The main image for this page
http://dali.dartmouth.edu/projects/

which is this image:
https://static1.squarespace.com/static/551cbdc5e4b0cd11d2597487/5640122ae4b01117a3c30083/5bfdaa8f03ce6431a604973d/1543421216079/SPLASH+PAGE.png?format=1000w

**Comment by jcheong0428** [comment]
added in commit https://github.com/lineatkaf/lineatkaf.github.io/commit/c684f1b90415a008cfc630561681a1b810462828
