### ISSUE TITLE
reported not working on certain Chrome version

### ISSUE THREAD

**Issue by jcheong0428** [lineatkaf/lineatkaf.github.io#9]
One of our testers reported that it's not working on their `Chrome Version 71.0.3578.98 (Official Build) (64-bit)` although working in Firefox.

**Comment by ejolly** [comment]
This could be due to our js being picked up by a browser plugin (e.g. adblocker). Maybe we can clean up the js a bit to handle this? Must be a pretty common issue for other general js apps
